sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

# safelist
branches:
  only:
  - travis_ci

script:
    - ./gradlew buildDocker

after_success:
  - if [ "$TRAVIS_BRANCH" == "travis_ci" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push elkaprojects/notifyme;
    fi
